### ISSUE TITLE
What should do when we use the data collected by myself

### ISSUE THREAD

**Issue by zhousuyu1111** [OpenRobotLab/VLM-Grounder#1]
I want to use the data collected by my own RGBD camera from three different perspectives to implement this model. How should I implement it

**Comment by RunsenXu** [comment]
Hi, 

Thanks for your interest in our work. Please refer to the method section of our paper. To quickly run the whole process, you can skip the image matching by PATS and view-preselection. And you need to re-implement the SceneInfoHandler https://github.com/OpenRobotLab/VLM-Grounder/blob/main/vlm_grounder/utils/info_handler.py, which should be easy, to handle projection for your own data.
