### ISSUE TITLE
How to reduce the amount of data

### ISSUE THREAD

**Issue by ninuan** [OpenRobotLab/VLM-Grounder#3]
As the dataset of scannet is too large, can I know the required files under scannt/scene0000_00, I would like to try if I can download the corresponding type of files to reduce the download time. Or if there are options for smaller datasets could you advise, thanks a lot! :）

**Comment by RunsenXu** [comment]
Hi,

Basically, you can check the codes here: https://github.com/OpenRobotLab/VLM-Grounder/blob/2c946f743538d33940fff18f068e92a1bf58d5a7/data/scannet/tools/batch_load_scannet_data.py#L149. You need the segmentation file, the *.sens file, and the .txt file.

**Comment by ninuan** [comment]
Thanks, i will have a try.

**Comment by hm123450** [comment]
hello, can i ask how can you get the scannet data? Did you sent the tos file and get the link? I search the internet and I'm not sure whether China can get the access.

**Comment by hm123450** [comment]
This is what I see in CSDN. "作者您好,非常感谢您提供的数据集下载链接，大陆境内貌似无法访问官方提供的链接了，冒昧问下可以提供该数据集的其他部分数据吗？特别是{{scan_name}}.txt文件，万分感谢！--邮箱"

**Comment by ninuan** [comment]
> This is what I see in CSDN. "作者您好,非常感谢您提供的数据集下载链接，大陆境内貌似无法访问官方提供的链接了，冒昧问下可以提供该数据集的其他部分数据吗？特别是{{scan_name}}.txt文件，万分感谢！--邮箱"
Can you give me your email, i will give you a link to download it. :)

**Comment by RunsenXu** [comment]
To downloading the data from mainland China, maybe consider https://opendatalab.com/OpenDataLab/ScanNet_v2/tree/main

**Comment by hm123450** [comment]
Thank you very much ! I will try.

**Comment by hm123450** [comment]
> Thanks, i will have a try.

Hello, my QQ number is 2464882060. May I add you as a friend to discuss the dataset download?

**Comment by hm123450** [comment]
> Thanks, i will have a try.

My email is 2464882060@stu.xjtu.edu.cn. I tried to download using the official link. The txt, ply, json, files are small, but the sens files are very large. I would like to know how big were the files you finally downloaded?
